#pragma once
#include <lvgl.h>

// The faces this interface draws with, and the only ones it may draw with.
//
// LVGL's built-in Montserrat faces carry ASCII, a degree sign and a bullet -
// nothing else. Every accent in the six Latin languages this product speaks is
// missing from them, and LVGL renders a character it has no glyph for as a
// blank box while logging nothing. That is why the translations were written
// without accents: not a style choice, a font that could not draw them.
//
// These are generated by scripts/make-ui-font.sh from the same two source fonts
// LVGL uses, with the same symbol list plus the sun, over a range that covers
// French, German, Spanish, Italian, Portuguese and Polish. Same metrics, same
// look, same LV_SYMBOL_* - a wider alphabet.
//
// Use these names, never lv_font_montserrat_*. The built-ins are switched off
// in lv_conf.h so the mistake does not link.
extern "C" {
LV_FONT_DECLARE(font_ui_12)
LV_FONT_DECLARE(font_ui_14)
LV_FONT_DECLARE(font_ui_16)
LV_FONT_DECLARE(font_ui_20)
LV_FONT_DECLARE(font_ui_24)

// Montserrat SemiBold, text only, for the ONE place weight is used: a screen's
// title. Everything else - rows, buttons, values, captions - is Medium, and
// that is what lets the title stand out at all. Weight everywhere is weight
// nowhere.
LV_FONT_DECLARE(font_ui_bold_16)

// JetBrains Mono, for the one screen that needs columns: the NFC tester's page
// dump. Space, 0-9, A-F and the x of "0x" - twenty glyphs, because that is all
// a hex dump contains. Nothing else in this interface uses it, and nothing else
// should: a monospace face is for data that lines up, not for prose.
LV_FONT_DECLARE(font_ui_mono_16)
}
