#!/usr/bin/env python3
"""Generated files must match what their generator produces, right now.

The incident: firmware/include/tigertag_db.h is banner-marked "GENERATED by
gen_db.py - do NOT edit by hand", and had been edited by hand. The edit was
harmless in itself - one comment line translated - but it proved the file and
its stated source had come apart, and nothing anywhere would have said so. The
generator could not even run at the time, so re-running it was not a thing
anyone did.

A "do not edit by hand" banner that nothing verifies is a banner that will be
ignored again. This re-runs the generator into a temporary directory and
compares. It never writes to the tree: a checker that repairs what it finds
stops being evidence of anything.
"""

import pathlib
import shutil
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent

# (generator, the file it owns). Add a row when a generator is added; the point
# is that this list is the registry, not a convention someone remembers.
# (command, the file it owns). The command is a list because not every
# generator is a bare script: the bitmap converter takes its source and its
# destination as arguments, and a wrapper script whose only job is to hold those
# arguments would be a second place the filename lives.
GENERATED = [
    (["firmware/tools/tigertag_db/gen_db.py"],
     REPO / "firmware" / "include" / "tigertag_db.h"),
    (["scripts/gen-font-range.py"],
     REPO / "scripts" / "font_range.json"),
    (["scripts/make-rgb565-header.py", "assets/TigerSpoolRFID-BootScreen.png",
      "--name", "SPLASH", "--out", "firmware/include/splash.h"],
     REPO / "firmware" / "include" / "splash.h"),
    (["scripts/make-ui-font.sh"],
     REPO / "firmware" / "src" / "ui" / "font_ui_16.c"),
    (["scripts/make-web-asset-header.py", "installer/tiger-icon.svg",
      "--name", "TIGER_ICON_SVG", "--out", "firmware/include/web_assets.h"],
     REPO / "firmware" / "include" / "web_assets.h"),
]

# A generator exiting with this says "I could not check", which is a different
# answer from "it does not match". gen-font-range.py uses it when the LVGL
# source is absent, as it is in a fresh clone. Reported, never silently passed:
# CI always has the library and proves the fact there.
SOURCE_UNAVAILABLE = 3


def main() -> int:
    if not GENERATED:
        # An empty input set is a broken checker, never a pass.
        print("error: no generated files registered - this check is checking nothing",
              file=sys.stderr)
        return 2

    failures = 0
    unverifiable = []
    for command, committed in GENERATED:
        rel = committed.relative_to(REPO)
        generator = REPO / command[0]
        if not generator.exists():
            print(f"error: generator missing: {command[0]}", file=sys.stderr)
            failures += 1
            continue
        if not committed.exists():
            print(f"error: generated file missing: {rel}", file=sys.stderr)
            failures += 1
            continue

        # Run the generator against a copy of the tree's output path, so the
        # committed file is never touched even if the generator misbehaves.
        with tempfile.TemporaryDirectory() as tmp:
            backup = pathlib.Path(tmp) / committed.name
            shutil.copy2(committed, backup)
            # Not every generator is Python. The font converter is a shell
            # script because the tool it drives is one; hard-coding the
            # interpreter here would have quietly run it as Python and
            # reported "failed to run" for the wrong reason.
            runner = [sys.executable] if command[0].endswith(".py") else ["bash"]
            proc = subprocess.run(runner + command,
                                  capture_output=True, text=True, cwd=REPO)
            produced = committed.read_bytes()
            shutil.copy2(backup, committed)   # restore before judging

            if proc.returncode == SOURCE_UNAVAILABLE:
                unverifiable.append(
                    f"{rel}: {(proc.stderr or proc.stdout).strip().splitlines()[0]}")
                continue

            if proc.returncode != 0:
                print(f"error: {command[0]} failed to run:", file=sys.stderr)
                print((proc.stderr or proc.stdout).strip()[:800], file=sys.stderr)
                failures += 1
                continue

            if produced != backup.read_bytes():
                print(f"error: {rel} does not match {command[0]}", file=sys.stderr)
                how = "python3" if command[0].endswith(".py") else "bash"
                print(f"       regenerate it: {how} " + " ".join(command),
                      file=sys.stderr)
                print("       do not hand-edit it back into agreement.", file=sys.stderr)
                failures += 1

    for u in unverifiable:
        print(f"note: {u}", file=sys.stderr)
    tail = (f", {len(unverifiable)} unverifiable here (CI proves these)"
            if unverifiable else "")
    print(f"checked {len(GENERATED) - len(unverifiable)} generated file(s), "
          f"{failures} out of date{tail}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
