#!/usr/bin/env python3
"""Extract the compiled UI font's character range into a committed fact.

    python3 scripts/gen-font-range.py

The range is a property of the build, recorded on the `Opts:` line the font
converter writes into each generated face.

It used to be read out of LVGL's own font sources under firmware/.pio/libdeps,
which a fresh clone does not have - so this generator, and every guard that
needed the range, could not run until somebody ran `pio pkg install`. The faces
are ours now and they are committed, so the fact is read from the repository
itself and the build tree is not needed at all. One caveat in CLAUDE.md went
away with it.

Exits 3, distinctly, when no face is found - "I could not check" is a different
answer from "it does not match", and check-generated.py reports them
differently.
"""

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "scripts" / "font_range.json"

SOURCE_UNAVAILABLE = 3


def main() -> int:
    # The mono face is deliberately NOT part of this.
    #
    # Every other face carries the same wide range, and that shared range is
    # what check-ui-fonts.py tests drawn strings against. font_ui_mono_* is a
    # twenty-glyph subset - space, 0-9, A-F, x - compiled for one screen, the
    # NFC tester's page dump, whose text is hex generated at runtime rather than
    # a literal anybody could get wrong. Folding its range into the union would
    # collapse the shared range to those twenty characters and the check would
    # stop meaning anything; leaving it out keeps the check honest and costs a
    # face that no literal is ever drawn in.
    sources = sorted(f for f in (REPO / "firmware" / "src" / "ui").glob("font_ui_*.c")
                     if "_mono_" not in f.name)
    if not sources:
        print("no generated UI face under firmware/src/ui - "
              "run 'bash scripts/make-ui-font.sh'", file=sys.stderr)
        return SOURCE_UNAVAILABLE

    specs = {}
    for src in sources:
        # Only the banner: these files are hundreds of kilobytes of glyph data.
        # The FIRST -r only. Each face is built from two fonts and therefore
        # carries two ranges: the text one, and LVGL's symbol list. The symbols
        # are icons rather than characters and no guard should be checking a
        # translation against them.
        banner = src.read_text(errors="replace")[:4096]
        m = re.search(r"-r\s+([0-9A-Fa-fx,\-]+)", banner)
        if m:
            specs[src.name] = m.group(1)

    if not specs:
        print(f"found {len(sources)} font source(s) but no '-r' range in any "
              "banner - the font converter's option line has changed shape",
              file=sys.stderr)
        return 1

    distinct = sorted(set(specs.values()))
    if len(distinct) > 1:
        # Every enabled size must carry the same glyphs, or a string is
        # drawable at 14 px and a blank box at 20 px.
        print("the generated UI faces do not share one range:",
              file=sys.stderr)
        for name, spec in sorted(specs.items()):
            print(f"  {name}: {spec}", file=sys.stderr)
        return 1

    OUT.write_text(json.dumps({
        "_comment": "GENERATED by scripts/gen-font-range.py - do NOT edit by hand.",
        "spec": distinct[0],
        "read_from": sorted(specs)[0],
        "sizes": len(specs),
    }, indent=2) + "\n")
    print(f"OK -> {OUT.relative_to(REPO)}   ({distinct[0]}, "
          f"{len(specs)} font size(s) agree)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
